def page_number_artist_map():
    pna_map = {
        "48": "Simon Dörken 2022",
        "47": "Philipp Brunke",
        "46": "Weller Vol.2",
        "45": "Naaman Wakim",
        "44": "David Broghammer",
        "43": "Nouki",
        "41": "Marcus K. und Weige (Topshake Soulknights)",
        "40": "Samba Gueye",
        "39": "Nicolas Schröter und Simon Dörken",
        "38": "Publikum Spezial",
        "37": "Lukas Lehmann",
        "36": "Gerald Wrede",
        "35": "Charalampos Lazos",
        "34": "Hendrik Reckermann",
        "33": "Hüseyin Köroglu",
        "32": "Timo Wiegand",
        "31": "Nicolas Schröter & Simon Dörken",
        "30": "Weller",
        "29": "Arndt Jahraus",
        "28": "Maya Hirsch",
        "27": "New Age/New Space/Ambient Open Air",
        "26": "Publikum Spezial",
        "25": "Marius Schmidt",
        "24": "James Dean Brown",
        "23": "Koloman",
        "22": "Lolo Blümler",
        "21": "Nicolas Schröter/Hannes Michels/Simon Dörken",
        "20": "Konstantin Papageorgiou",
        "19": "Robert JazzMadass Lochmann",
        "18": " Robert Herz (Okta Logue)",
        "17": "Markos (Manges)",
        "16": "Publikum Spezial",
        "15": "Sven Helwig",
        "14": "Daniele Iezzi",
        "13": "Pedo Knopp",
        "12": "Thur Deephrey",
        "11": "Simon Dörken",
        "10": "Christian Beetz",
        "9": "For a Better Tomorrow",
        "8": "Thomas Hammann",
        "7": "Sommer Spezial im Osthang",
        "6": "Jaques Tectile",
        "5": "Hannes Michels",
        "4": "Nicolas Schröter",
        "3": "Benedikt Frey",
        "2": "Philip Berg",
        "1": "Simon Dörken",
    }
    return pna_map
